import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { gql } from "@apollo/client";
import client from "../apollo-client";

const Home: NextPage = ({ repos }) => { //todo: fix this issue
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          {repos.map((repo) => (
            <div key={repo.name} className={styles.card}>
              <p>
                {repo.name}
              </p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {

  // const { data } = await client.query({
  //   query: gql`
  //     query ExampleQuery {
  //       countries {
  //         code
  //         name
  //         emoji
  //       }
  //     }
  //   `,
  // });

  const { data } = await client.query({
    query: gql`
      query AllRepos {
        viewer {
          repositories(affiliations: OWNER, first: 10) {
            nodes {
              name
            }
          }
        }
      }
    `,
  });

  return {
    props: {
      repos: data.viewer.repositories.nodes.slice(0, 4),
    },
  };
}


export default Home
